#include "module.h"

static const char *tcWrenMathModule =
"class Vector2 {\n"
" construct new(x, y) {\n"
"  _x = x\n"
"  _y = y\n"
" }\n"
" x { _x }\n"
" y { _y }\n"
// " foreign =(other)\n"
" +(other) { Vector2.new(_x + other.x, _y + other.y) }\n"
" -(other) { Vector2.new(_x - other.x, _y - other.y) }\n"
" *(value) { Vector2.new(_x * other, _y * other) }\n"
" /(value) { Vector2.new(_x / other, _y / other) }\n"
" x=(value) { _x = value }\n"
" y=(value) { _y = value }\n"
// " dot(other) {}\n"
" static zero() { Vector2.new(0, 0) }\n"
"}\n"
"class Transform {\n"
" position { _position }\n"
" position=(value) { _position = value }\n"
" scale { _size }\n"
" scale=(value) { _size = value }\n"
" angle { _angle }\n"
" angle=(value) { _angle = value }\n"
" construct new(x, y) {\n"
"  _position = Vector2.new(x, y)\n"
"  _size = Vector2.new(1,1)\n"
"  _angle = 0\n"
" }\n"
"}\n";